# Generated by Django 2.2.6 on 2020-05-12 23:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200512_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
