# Generated by Django 2.2.6 on 2020-05-18 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_auto_20200517_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza'),
        ),
    ]
